window.IMMBA = {
  news: [
    {
      id: "spring-2027",
      date: "2026-08-19",
      pin: true,
      tagEn: "Admissions",
      tagZh: "招生",
      titleEn: "Spring 2027, apply now (14 Sep – 14 Oct) — international students only",
      titleZh: "Spring 2027 招生進行中（9/14–10/14）— 僅限外國學生",
      bodyEn: "The Spring 2027 intake for international applicants is open from 14 September to 14 October. Apply online through the FJCU international degree application system and submit the required documents listed on the Admissions page.",
      bodyZh: "外國學生 Spring 2027 申請期間為 9 月 14 日至 10 月 14 日。請至輔大外國學生入學申請系統線上報名，並依招生頁所列文件繳交資料。"
    },
    {
      id: "career-platform",
      date: "2025-01-30",
      pin: true,
      tagEn: "Careers",
      tagZh: "職涯",
      titleEn: "College of Management Career Platform — job openings",
      titleZh: "管理學院職涯平台 — 工作職缺",
      bodyEn: "The College of Management career platform lists internships and full-time openings for graduate students. Check regularly for new postings.",
      bodyZh: "管理學院職涯平台提供碩士生實習與正職職缺資訊，請定期關注最新公告。"
    },
    {
      id: "info-session-local",
      date: "2026-09-29",
      pin: false,
      tagEn: "Events",
      tagZh: "活動",
      titleEn: "29 Sep admissions info session recap — local applications open tomorrow",
      titleZh: "9/29 招生說明會回顧｜本地生報名即將開始",
      bodyEn: "The programme chair hosted an information session covering curriculum, dual degrees, and career paths. Local applicants should follow the Chinese admissions calendar for screening and master’s-entry rounds.",
      bodyZh: "主任於說明會介紹課程、雙聯學位與職涯發展。本地生請依甄試與碩士班招生時程報名。"
    },
    {
      id: "two-years",
      date: "2026-09-22",
      pin: false,
      tagEn: "Programme",
      tagZh: "學程",
      titleEn: "Two years, more than one master’s degree",
      titleZh: "碩士兩年，可以有多大可能？",
      bodyEn: "Students may complete the two-year FJCU imMBA or pursue a dual master’s pathway with UM-Flint, KEDGE, or IQS, earning two degrees when both institutions’ requirements are met.",
      bodyZh: "學生可選擇兩年輔大 imMBA，或於 UM-Flint、KEDGE、IQS 攻讀雙碩士，於符合雙方畢業規定後取得兩個學位。"
    },
    {
      id: "intl-info",
      date: "2026-09-15",
      pin: false,
      tagEn: "Events",
      tagZh: "活動",
      titleEn: "International students: get to know Fu Jen imMBA at our info session",
      titleZh: "你身邊有正在考慮 MBA 的國際學生嗎？",
      bodyEn: "Join an English-language introduction to AACSB-accredited study at Fu Jen, classroom diversity, and the dual-degree options in the United States, France, and Spain.",
      bodyZh: "歡迎參加全英語學程說明，了解 AACSB 認證、課堂國際組成，以及美國、法國、西班牙雙聯學位。"
    },
    {
      id: "ai-product",
      date: "2026-09-02",
      pin: false,
      tagEn: "Faculty",
      tagZh: "師資",
      titleEn: "90 seconds with the professor — AI × Product",
      titleZh: "90 Seconds with the Professor｜AI × Product",
      bodyEn: "Faculty share how AI is reshaping product development and why managers need both analytical judgement and market sense.",
      bodyZh: "教師分享人工智慧如何改變產品開發，以及管理者為何需要兼具分析判斷與市場 sensemaking。"
    },
    {
      id: "data-analytics",
      date: "2026-08-26",
      pin: false,
      tagEn: "Curriculum",
      tagZh: "課程",
      titleEn: "New course spotlight: Data Analytics for International Business",
      titleZh: "新課介紹｜Data Analytics for International Business",
      bodyEn: "A new elective strengthens quantitative decision-making for cross-border markets, complementing marketing, operations, and strategy.",
      bodyZh: "新選修強化跨國市場的量化決策能力，與行銷、營運與策略課程相互補強。"
    },
    {
      id: "ai-digital-product",
      date: "2026-08-19",
      pin: false,
      tagEn: "Curriculum",
      tagZh: "課程",
      titleEn: "New course spotlight: AI-Assisted Digital Product Development",
      titleZh: "新課介紹｜AI-Assisted Digital Product Development",
      bodyEn: "Students work with AI-assisted workflows to frame, prototype, and evaluate digital products in an international management context.",
      bodyZh: "課程引導學生以 AI 輔助流程構思、原型與評估數位產品，並置於國際管理情境中思考。"
    },
    {
      id: "iqs-spotlight",
      date: "2026-07-29",
      pin: false,
      tagEn: "Partners",
      tagZh: "合作",
      titleEn: "Partner spotlight: IQS School of Management",
      titleZh: "合作夥伴｜IQS School of Management",
      bodyEn: "IQS in Barcelona is AACSB accredited and offers dual-degree options in international marketing and industrial business management.",
      bodyZh: "位於巴塞隆納的 IQS 具 AACSB 認證，提供國際行銷與工業企業管理等雙聯學位選項。"
    },
    {
      id: "leaders",
      date: "2026-07-22",
      pin: false,
      tagEn: "Insight",
      tagZh: "觀點",
      titleEn: "What kind of leaders should we cultivate in a rapidly changing world?",
      titleZh: "當世界快速變動，我們該培養什麼樣的領導者？",
      bodyEn: "The programme’s aim remains practical: develop managers who can work across cultures, technologies, and markets with ethical judgement.",
      bodyZh: "學程目標明確：培養能在文化、科技與市場之間工作、並具備倫理判斷的管理人才。"
    }
  ],
  faculty: [
    {
      name: "Yi-Ning Tu",
      nameZh: "杜逸寧",
      roleEn: "Associate Professor and Chair, imMBA",
      roleZh: "副教授兼國際經營管理碩士班主任",
      eduEn: "Ph.D. in Information Management, National Chengchi University",
      eduZh: "政治大學資訊管理學博士",
      specEn: "Data mining, text mining, AI, machine learning, information retrieval",
      specZh: "資料探勘、文字探勘、人工智慧、機器學習、資訊檢索",
      tel: "#3988, LM208-2",
      email: "082435@mail.fju.edu.tw",
      web: "https://sites.google.com/view/yiningtu"
    },
    {
      name: "Michael T. S. Lee",
      nameZh: "李天行",
      roleEn: "Chair Professor",
      roleZh: "講座教授",
      eduEn: "Ph.D. in Operations Research and Industrial Engineering, University of Texas at Austin",
      eduZh: "美國德州大學奧斯汀校區作業研究與工業工程博士",
      specEn: "Operations research and industrial engineering",
      specZh: "作業研究與工業工程",
      tel: "#2905, SL228",
      email: "036665@mail.fju.edu.tw"
    },
    {
      name: "Yaonan Lin",
      nameZh: "林瑤南",
      roleEn: "Professor",
      roleZh: "教授",
      eduEn: "Ph.D. in Marketing, Golden Gate University, San Francisco",
      eduZh: "美國金門大學行銷學博士",
      specEn: "Marketing management",
      specZh: "行銷管理",
      tel: "#2735, #2021",
      email: "065999@mail.fju.edu.tw"
    },
    {
      name: "Yu-Ming Hsu",
      nameZh: "許聿銘",
      roleEn: "Associate Professor, Director of MS Program in Technology Management",
      roleZh: "副教授兼科技管理碩士班主任",
      eduEn: "Ph.D. in International Business, National Taiwan University",
      eduZh: "臺灣大學國際企業博士",
      specEn: "Marketing, digital marketing, social commerce, international business",
      specZh: "行銷管理、數位行銷、社群商務、國際企業",
      tel: "#3977, SL225",
      email: "155456@mail.fju.edu.tw"
    },
    {
      name: "Chih-An Lin",
      nameZh: "林芷安",
      roleEn: "Associate Professor, Director of the Academic Exchange Center",
      roleZh: "副教授兼學術交流中心主任",
      eduEn: "Ph.D. in International Business, National Taiwan University",
      eduZh: "臺灣大學國際企業博士",
      specEn: "Supply chain, media communication, integrated marketing, brand management",
      specZh: "供應鏈管理、媒體溝通、整合行銷、品牌管理",
      tel: "#2924, SL221",
      email: "144629@mail.fju.edu.tw"
    },
    {
      name: "Kai-Ping Huang",
      nameZh: "黃凱平",
      roleEn: "Associate Professor",
      roleZh: "副教授",
      eduEn: "Ph.D. in Business Administration, University of Technology Sydney",
      eduZh: "澳洲悉尼科技大學企業管理博士",
      specEn: "Business administration",
      specZh: "企業管理",
      tel: "#2906",
      email: "129741@mail.fju.edu.tw"
    },
    {
      name: "Hsiang-Ching Tseng",
      nameZh: "曾祥景",
      roleEn: "Associate Professor",
      roleZh: "副教授",
      eduEn: "Ph.D. in Marketing, National Chengchi University",
      eduZh: "政治大學行銷學博士",
      specEn: "Marketing management",
      specZh: "行銷管理",
      tel: "#2737",
      email: "142652@mail.fju.edu.tw"
    },
    {
      name: "Mei-Chun Lin",
      nameZh: "林美純",
      roleEn: "Associate Professor",
      roleZh: "副教授",
      eduEn: "Ph.D. in Industrial and Information Management, National Cheng Kung University",
      eduZh: "成功大學工業與資訊管理博士",
      specEn: "AI in industry, service marketing, competitive strategy, supply chain",
      specZh: "產業AI應用、服務行銷、競爭策略、供應鏈管理",
      tel: "#2968, SL408",
      email: "151308@mail.fju.edu.tw"
    },
    {
      name: "Shu-Ling Cheng",
      nameZh: "鄭淑玲",
      roleEn: "Associate Professor",
      roleZh: "副教授",
      eduEn: "Ph.D. in Business Administration, National Cheng Kung University",
      eduZh: "成功大學企業管理博士",
      specEn: "Strategic management, marketing research, data analysis, international finance",
      specZh: "策略管理、行銷研究、資料分析、國際財務管理",
      tel: "#2725, SL211",
      email: "151667@mail.fju.edu.tw"
    },
    {
      name: "Pi-Chan Hu",
      nameZh: "胡碧嬋",
      roleEn: "Associate Professor",
      roleZh: "副教授",
      eduEn: "Ph.D. in Applied Linguistics, National Chengchi University",
      eduZh: "政治大學應用語言學博士",
      specEn: "International business negotiation, translation, interpretation, applied linguistics",
      specZh: "國際商務談判、英語口筆譯、應用語言學",
      tel: "#2145",
      email: "128144@mail.fju.edu.tw"
    },
    {
      name: "Tsui-Lin Chiang",
      nameZh: "姜翠林",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Business Administration, Fu Jen Catholic University",
      eduZh: "輔仁大學企業管理博士",
      specEn: "Economics, business governance, financial management, investment",
      specZh: "經濟學、公司治理、財務管理、投資",
      tel: "#2852, SL472",
      email: "051266@mail.fju.edu.tw"
    },
    {
      name: "Shu-wen Lin",
      nameZh: "林淑雯",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ed.D., School of Education, Durham University",
      eduZh: "英國杜倫大學教育博士",
      specEn: "English for general and specific purposes, Global Englishes",
      specZh: "一般與專業英語、全球英語",
      tel: "#3362, SF829",
      email: "156503@mail.fju.edu.tw"
    },
    {
      name: "Meng-Hsien Yen",
      nameZh: "顏孟賢",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Business Policy, National Chengchi University",
      eduZh: "政治大學企業政策博士",
      specEn: "General management and business policy",
      specZh: "一般管理與企業政策",
      tel: "#2648",
      email: "145785@mail.fju.edu.tw"
    },
    {
      name: "Hao-Hsin Hsu",
      nameZh: "徐浩信",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Management Science, National Chiao Tung University",
      eduZh: "交通大學管理科學博士",
      specEn: "Organizational behavior, workplace health psychology, HRM",
      specZh: "組織行為、職場健康心理、人力資源管理",
      tel: "#2771",
      email: "144779@mail.fju.edu.tw"
    },
    {
      name: "Kai-Pin Huang",
      nameZh: "黃凱斌",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Industrial Engineering and Management, National Chiao Tung University",
      eduZh: "交通大學工業工程與管理博士",
      specEn: "Statistical inference, quality engineering, data mining, AI in energy",
      specZh: "統計推論、品質工程、資料探勘、再生能源AI應用",
      tel: "#6265",
      email: "152400@mail.fju.edu.tw"
    },
    {
      name: "Lai Ferry Sugianto",
      nameZh: "Lai Ferry Sugianto",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Finance, National Chung Cheng University",
      eduZh: "中正大學財務金融博士",
      specEn: "Investment, behavioral finance, green finance, climate finance, ESG",
      specZh: "投資、行為財務、綠色金融、氣候金融、ESG",
      tel: "#2678",
      email: "158325@mail.fju.edu.tw"
    },
    {
      name: "Tsang-Hsien Wang",
      nameZh: "王蒼憲",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Management, National Taiwan University of Science and Technology",
      eduZh: "臺灣科技大學管理博士",
      specEn: "Consumer behavior, marketing, innovation and product management, branding",
      specZh: "消費者行為、行銷管理、創新與產品管理、品牌管理",
      tel: "#3931",
      email: "167167@mail.fju.edu.tw"
    },
    {
      name: "Chia-Hua Lin",
      nameZh: "林佳樺",
      roleEn: "Assistant Professor",
      roleZh: "助理教授",
      eduEn: "Ph.D. in Psychology, National Chung Cheng University",
      eduZh: "中正大學心理學博士",
      specEn: "Organizational behavior, industrial and organizational psychology",
      specZh: "組織行為、工商心理學",
      tel: "#2966",
      email: "167208@mail.fju.edu.tw"
    },
    {
      name: "Hui-Mei Wang",
      nameZh: "王慧美",
      roleEn: "Part-time Associate Professor, former imMBA Chair",
      roleZh: "兼任副教授（前國際經營管理碩士班主任）",
      eduEn: "Ph.D. in International Business, National Taiwan University",
      eduZh: "臺灣大學國際企業博士",
      specEn: "International business and international marketing",
      specZh: "國際企業、國際行銷",
      tel: "",
      email: "wanghm.tw@gmail.com"
    }
  ]
};
